MedPrompts sched on-time, EMAs are randomly-scheduled within a user's open time slots, EMA prompt now with just 1 button.
BIG NOTE: YOU CANNOT USE SINGLE-QUOTES IN THE INCOMING APP-CFG! Using a
word like "it's" will break the entirety of PRNM and cause the error on
the following line. Need a fix for this:

org.mozilla.javascript.EcmaError: SyntaxError: missing ; before
statement (<engine>#1(eval)#1)

2 tests fail, both on the same line.

onEMANo removed due to being unnecessary.